# Pandas-DataFrame And Series

#### Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
import pandas as pd

In [5]:
## Series
##A Pandas Series is a one-dimensional array-like object that can h
import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [8]:
data = {"a":1,"b":2,"c":3}
print(pd.Series(data))

a    1
b    2
c    3
dtype: int64

In [9]:
data =[10,20,30]
index = ["a","b","c"]
seri_list= pd.Series(data,index=index)
print(seri_list)

a    10
b    20
c    30
dtype: int64

In [13]:
## Dataframe
## create a Dataframe from a dictionary oof list
data={
'Name': ['kunal', 'John', 'Jack'],
'Age': [25,30,45],
'City': ['Bangalore', 'New York', 'Florida']
}
df=pd.DataFrame (data)
print(df)

    Name  Age       City
0  kunal   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [14]:
import numpy as np
np.array(df)

array([['kunal', 25, 'Bangalore'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [15]:
data=[
{'Name': 'kunal', 'Age': 32, 'City': 'Bangalore'},
{'Name': 'John', 'Age': 34, 'City': 'Bangalore'},
{'Name': 'Bappy', 'Age': 32, 'City': 'Bangalore'},
{'Name': 'JAck', 'Age': 32, 'City': 'Bangalore'}]
df=pd.DataFrame (data)
print(df)

    Name  Age       City
0  kunal   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [20]:
df = pd.read_csv("Teen_Mental_Health_Dataset.csv")
df.head(3)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0

In [21]:
df.tail(3)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [23]:
df.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

In [29]:
data=[
{'Name': 'kunal', 'Age': 32, 'City': 'Bangalore'},
{'Name': 'John', 'Age': 34, 'City': 'Bangalore'},
{'Name': 'Bappy', 'Age': 30, 'City': 'Bangalore'},
{'Name': 'Jack', 'Age': 45, 'City': 'Bangalore'}]
df=pd.DataFrame (data)
print(df)

    Name  Age       City
0  kunal   32  Bangalore
1   John   34  Bangalore
2  Bappy   30  Bangalore
3   Jack   45  Bangalore

In [30]:
df

    Name  Age       City
0  kunal   32  Bangalore
1   John   34  Bangalore
2  Bappy   30  Bangalore
3   Jack   45  Bangalore

In [31]:
df["Name"]

0    kunal
1     John
2    Bappy
3     Jack
Name: Name, dtype: str

In [49]:
df.loc[2:3,["Name","City"]]

    Name       City
2  Bappy  Bangalore
3   Jack  Bangalore

In [46]:
df.iloc[0]

Name        kunal
Age            32
City    Bangalore
Name: 0, dtype: object

In [57]:
df.iloc[2:,[0,2]]

    Name       City
2  Bappy  Bangalore
3   Jack  Bangalore

In [61]:
print(df.at[2,"Name"])
print(df.at[2,"City"])

Bappy
Bangalore

In [63]:
df

    Name  Age       City
0  kunal   32  Bangalore
1   John   34  Bangalore
2  Bappy   30  Bangalore
3   Jack   45  Bangalore

In [69]:
print(df.iat[0,0])
print(df.iat[0,1])
print(df.iat[0,2])

kunal
32
Bangalore

In [89]:
df["Salary"]=[10000,8000,3000,4000]
df

  First_Name  Age       City  Salary
0      kunal   32  Bangalore   10000
1       John   34  Bangalore    8000
2      Bappy   30  Bangalore    3000
3       Jack   45  Bangalore    4000

In [90]:
df.rename(columns={"Name":"First_Name"},inplace= True)
df

  First_Name  Age       City  Salary
0      kunal   32  Bangalore   10000
1       John   34  Bangalore    8000
2      Bappy   30  Bangalore    3000
3       Jack   45  Bangalore    4000

In [91]:
df.drop("Salary",axis=1)

  First_Name  Age       City
0      kunal   32  Bangalore
1       John   34  Bangalore
2      Bappy   30  Bangalore
3       Jack   45  Bangalore

In [92]:
df.drop("Salary",axis=1,inplace=True)

In [93]:
df

  First_Name  Age       City
0      kunal   32  Bangalore
1       John   34  Bangalore
2      Bappy   30  Bangalore
3       Jack   45  Bangalore

In [94]:
df["Age"]=df["Age"]+1
df

  First_Name  Age       City
0      kunal   33  Bangalore
1       John   35  Bangalore
2      Bappy   31  Bangalore
3       Jack   46  Bangalore