In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
data = {
    'Age': [25, 30, np.nan, 35, 28],
    'Salary': [50000, np.nan, 60000, 80000, 70000],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Male'],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai'],
    'Purchased': ['Yes', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)
df

    Age   Salary  Gender     City Purchased
0  25.0  50000.0    Male    Delhi       Yes
1  30.0      NaN  Female   Mumbai        No
2   NaN  60000.0  Female    Delhi       Yes
3  35.0  80000.0    Male  Chennai        No
4  28.0  70000.0    Male   Mumbai       Yes

## Handle Missing Values

In [3]:
# Fill Age with mean
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Fill Salary with mean
df['Salary'].fillna(df['Salary'].mean(), inplace=True)

print(df)

    Age   Salary  Gender     City Purchased
0  25.0  50000.0    Male    Delhi       Yes
1  30.0  65000.0  Female   Mumbai        No
2  29.5  60000.0  Female    Delhi       Yes
3  35.0  80000.0    Male  Chennai        No
4  28.0  70000.0    Male   Mumbai       Yes

## Label Encoding (Gender & Purchased)

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])     # Male=1, Female=0
df['Purchased'] = le.fit_transform(df['Purchased'])  # Yes=1, No=0
df

    Age   Salary  Gender     City  Purchased
0  25.0  50000.0       1    Delhi          1
1  30.0  65000.0       0   Mumbai          0
2  29.5  60000.0       0    Delhi          1
3  35.0  80000.0       1  Chennai          0
4  28.0  70000.0       1   Mumbai          1

## One-Hot Encoding (City)

In [5]:
df = pd.get_dummies(df, columns=['City'])
df

    Age   Salary  Gender  Purchased  City_Chennai  City_Delhi  City_Mumbai
0  25.0  50000.0       1          1         False        True        False
1  30.0  65000.0       0          0         False       False         True
2  29.5  60000.0       0          1         False        True        False
3  35.0  80000.0       1          0          True       False        False
4  28.0  70000.0       1          1         False       False         True

## Scaling (Normalization)

In [6]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['Age', 'Salary']] = scaler.fit_transform(df[['Age', 'Salary']])
df

    Age    Salary  Gender  Purchased  City_Chennai  City_Delhi  City_Mumbai
0  0.00  0.000000       1          1         False        True        False
1  0.50  0.500000       0          0         False       False         True
2  0.45  0.333333       0          1         False        True        False
3  1.00  1.000000       1          0          True       False        False
4  0.30  0.666667       1          1         False       False         True

## Standardization

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df[['Age', 'Salary']] = scaler.fit_transform(df[['Age', 'Salary']])
df

,Age,Salary,Gender,Purchased,City_Chennai,City_Delhi,City_Mumbai
0,-1.382164e+00,-1.500000e+00,1,1,False,True,False
1,1.535738e-01,3.330669e-16,0,0,False,False,True
2,3.410023e-16,-5.000000e-01,0,1,False,True,False
3,1.689312e+00,1.500000e+00,1,0,True,False,False
4,-4.607213e-01,5.000000e-01,1,1,False,False,True

In [8]:
data = {

    'Purchased': ['Yes', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)
df

  Purchased
0       Yes
1        No
2       Yes
3        No
4       Yes

In [9]:
le = LabelEncoder()
df["Encoded"] = le.fit_transform(df["Purchased"])
df

  Purchased  Encoded
0       Yes        1
1        No        0
2       Yes        1
3        No        0
4       Yes        1

In [10]:
le.classes_ = le.classes_[::-1]

df["reverse"] = le.transform(df["Purchased"])
df

  Purchased  Encoded  reverse
0       Yes        1        0
1        No        0        1
2       Yes        1        0
3        No        0        1
4       Yes        1        0